UPDATE jxhifi.address SET city = 'Montreal', country = 'Canada', postal_code = 'H1A 2B3', state = 'QC', street = '10 Main St' WHERE id = 'ADR1';
UPDATE jxhifi.address SET city = 'Montreal', country = 'Canada', postal_code = 'H3A 2R7', state = 'QC', street = '100 Cherry Pl' WHERE id = 'ADR10';
UPDATE jxhifi.address SET city = 'Toronto', country = 'Canada', postal_code = 'M5J 2N2', state = 'ON', street = '110 Palm Way' WHERE id = 'ADR11';
UPDATE jxhifi.address SET city = 'Vancouver', country = 'Canada', postal_code = 'V6J 4A3', state = 'BC', street = '120 Fir St' WHERE id = 'ADR12';
UPDATE jxhifi.address SET city = 'Calgary', country = 'Canada', postal_code = 'T3A 5R6', state = 'AB', street = '130 Spruce Blvd' WHERE id = 'ADR13';
UPDATE jxhifi.address SET city = 'Montreal', country = 'Canada', postal_code = 'H3B 2V9', state = 'QC', street = '140 Chestnut Rd' WHERE id = 'ADR14';
UPDATE jxhifi.address SET city = 'Toronto', country = 'Canada', postal_code = 'M4C 1Z2', state = 'ON', street = '150 Aspen Dr' WHERE id = 'ADR15';
UPDATE jxhifi.address SET city = 'Toronto', country = 'Canada', postal_code = 'M4B 1B4', state = 'ON', street = '20 Elm St' WHERE id = 'ADR2';
UPDATE jxhifi.address SET city = 'Vancouver', country = 'Canada', postal_code = 'V5K 3Z4', state = 'BC', street = '30 Maple Ave' WHERE id = 'ADR3';
UPDATE jxhifi.address SET city = 'Calgary', country = 'Canada', postal_code = 'T2P 5C4', state = 'AB', street = '40 Oak Blvd' WHERE id = 'ADR4';
UPDATE jxhifi.address SET city = 'Montreal', country = 'Canada', postal_code = 'H2X 1Y7', state = 'QC', street = '50 Birch Rd' WHERE id = 'ADR5';
UPDATE jxhifi.address SET city = 'Toronto', country = 'Canada', postal_code = 'M5A 4E2', state = 'ON', street = '60 Cedar Ln' WHERE id = 'ADR6';
UPDATE jxhifi.address SET city = 'Vancouver', country = 'Canada', postal_code = 'V6B 5T1', state = 'BC', street = '70 Pine Ct' WHERE id = 'ADR7';
UPDATE jxhifi.address SET city = 'Ottawa', country = 'Canada', postal_code = 'K1A 0B1', state = 'ON', street = '80 Walnut Dr' WHERE id = 'ADR8';
UPDATE jxhifi.address SET city = 'Quebec City', country = 'Canada', postal_code = 'G1A 1C5', state = 'QC', street = '90 Poplar St' WHERE id = 'ADR9';
